config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  get 'site/home'
  get 'site/calendar'
  resources :sections
  get 'pages/home'
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#home"
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
    validates :title, :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo do |attachable|
        attachable.variant :thumb, resize_to_limit: [100, 100]
    end
    
    validates :title, :eventstart, :eventend, presence: true
    validate :cannot_have_more_than_four_featured

    def cannot_have_more_than_four_featured
        if (featured && (Event.where(featured: true).length > 3))
            errors.add(:featured, "can't be true because there are already 4 featured events")
        end
    end
end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :section
	validates :title, :page_type, presence: true
	has_one_attached :doc
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album
    has_one_attached :image
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :pages
    validates :title, :location, presence: true
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :featured, :allday, :eventstart, :eventend, :occurence, :details, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :position, :page_type, :destination, :visible, :content)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
  end
  def calendar
    @events = Event.where(featured: true)
    puts "\n\n\n\n\n\n\n\n\n\n"
    @months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    @now = DateTime.now
    puts "\n\n\n\n\n\n\n\n\n\n"
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HarmonyClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "custom" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav class="navbar">
      <div class="container-fluid" id="navbarContainer">
        <%= link_to "HARMONY CLUB OF WORCESTER", site_home_path, class: "navbar-brand text-light float-start" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
      <div class="navbar-nav">
        <%= link_to "New Link", new_page_path, class: "nav-link" %>
        <%= link_to "Calendar", site_calendar_path, class: "nav-link" %>
        <%= link_to "Events", events_path, class: "nav-link" %>
        <%= link_to "Sections", sections_path, class: "nav-link" %>
        <% Section.all.where(visible: true).each do |section| %>
          <%= link_to section.title, "#", class: "dropdown-toggle nav-link" %>
        <% end %>
      </div>
    </div>
    <div class="text-light">
        <%= yield %>
    </div>
    <div class="bg-danger">

    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div data-controller="event">
    <div>
      <%= form.label :page_type, style: "display: block" %>
      <%= form.select :page_type, ["Basic Page", "External URL", "Internal URL", "PDF"], {include_blank: true},
      data:{
        action: "change->event#display",
        "event-target": "page_type"
      } %>
    </div>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :section_id, style: "display: block" %>
      <%= form.number_field :section_id %>
    </div>

    <div>
      <%= form.label :position, style: "display: block" %>
      <%= form.number_field :position %>
    </div>


    <div>
      <%= form.label :destination, style: "display: block" %>
      <%= form.text_field :destination %>
    </div>

    <div>
      <%= form.label :visible, style: "display: block" %>
      <%= form.check_box :visible %>
    </div>

    <div data-event-target="content" class="hidden">
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= page.section_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= page.position %>
  </p>

  <p>
    <strong>Page type:</strong>
    <%= page.page_type %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= page.destination %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= page.visible %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New Menu Link</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>